(string-trim 
      '(#\Space #\Newline #\Backspace #\Tab 
        #\Linefeed #\Page #\Return #\Rubout) "This string
       ")

(handler-case (with-output-to-string (s) (sb-ext:run-program "/usr/bin/git" (list "init") :output s :directory "/home/acow/Desktop/gittest/")) (simple-error () nil))

(handler-case (with-output-to-string (s) (sb-ext:run-program "/usr/bin/git" (list "add" "-A") :output s :directory "/home/acow/Desktop/gittest/")) (simple-error () nil))

(handler-case (with-output-to-string (s) (sb-ext:run-program "/usr/bin/git" (list "commit" "-m" "Initial commit for the gittest project.  Automatically generated by cl-project-manager.") :output s :directory "/home/acow/Desktop/gittest/")) (simple-error () nil))
