(defvar *test-ids* (make-hash-table :test 'eql))
(defvar *test-names* (make-hash-table :test 'equal)) 
(defvar *test-tag-ids* (make-hash-table :test 'equal))
(defvar *test-tag-before-functions* (make-hash-table :test 'equal))
(defvar *test-tag-after-functions* (make-hash-table :test 'equal))
(defvar *test-directory* nil)
(defvar *test-id-paths* (make-hash-table :test 'equal))
(defvar *test-paths* (make-hash-table :test 'equal))
(defvar *test-results* nil)
(defvar *test-statistics* nil)
(defvar *test-id-before-functions* (make-hash-table :test 'eql))
(defvar *test-id-after-functions* (make-hash-table :test 'eql))
(defvar *test-empty-function* (lambda () nil))
