(defparameter *active-module-path* nil)
(defparameter *active-module-validated* nil)
(defparameter *active-module-config* nil)
(defparameter *test-dir-name* "tests/")
(defparameter *module-config-name* "module-config.meta")
(defparameter *test-config-name* "test-config.meta")
(defparameter *other-config-name* "config.meta")
(defparameter *authors* nil)
