(in-package #:peasant)

(defvar *active-module-path* nil)
(defvar *active-module-validated* nil)
(defvar *active-module-config* nil)
(defvar *test-dir-name* "tests/")
(defvar *module-config-name* "module-config.meta")
(defvar *test-config-name* "test-config.meta")
(defvar *other-config-name* "config.meta")
(defvar *authors* "Damien John Melksham")
